image: gitpod/workspace-base

tasks:

- name: SETUP - Install MAMBA and BUSCO
  init: |
    wget "https://github.com/conda-forge/miniforge/releases/download/24.3.0-0/Mambaforge-24.3.0-0-Linux-x86_64.sh"
    bash Mambaforge-24.3.0-0-Linux-x86_64.sh -b -p /workspace/mambaforge && rm Mambaforge-24.3.0-0-Linux-x86_64.sh
    /workspace/mambaforge/bin/mamba init bash

    source ${HOME}/.bashrc

    mamba create -n busco -c conda-forge -c bioconda busco=5.8.0 -y

    mamba clean --all -y
    
  command: |
    /workspace/mambaforge/bin/mamba init bash
    source ~/.bashrc
    mamba activate busco
    cd /workspace/busco/
    mkdir exercises
    cd exercises/
    mkdir exercise1 exercise2 exercise3 exercise4 exercise5 exercise6
    cd exercise1/
    wget ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/009/065/GCF_000009065.1_ASM906v1/GCF_000009065.1_ASM906v1_protein.faa.gz && gunzip GCF_000009065.1_ASM906v1_protein.faa.gz
    cd ../exercise2/
    wget ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/008/865/GCF_000008865.2_ASM886v2/GCF_000008865.2_ASM886v2_genomic.fna.gz && gunzip GCF_000008865.2_ASM886v2_genomic.fna.gz
    cd ../exercise5/
    mkdir batch_input
    cd batch_input
    wget ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/009/065/GCF_000009065.1_ASM906v1/GCF_000009065.1_ASM906v1_genomic.fna.gz && gunzip GCF_000009065.1_ASM906v1_genomic.fna.gz
    cp ../../exercise2/GCF_000008865.2_ASM886v2_genomic.fna .    
    cd ../../exercise6/
    mv ../bacteria_odb12.tar.gz .
    tar xzf bacteria_odb12.tar.gz
    cp exercise1/GCF_000008865.2_ASM886v2_genomic.fna .
    cd /workspace/busco/

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
    visibility: public

workspaceLocation: "/workspace"
